name: Check Size

on:
  pull_request:

jobs:
  check-size:
    name: Check Size
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Fetch bundletool
        run: |
          curl -s -L https://github.com/google/bundletool/releases/download/1.9.0/bundletool-all-1.9.0.jar --create-dirs -o bin/bundletool.jar
          chmod +x bin/bundletool.jar
          echo "#!/bin/bash" >> bin/bundletool
          echo 'java -jar $(dirname "$0")/bundletool.jar "$@"' >> bin/bundletool
          chmod +x bin/bundletool
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Save Size
        run: |
          mkdir -p ./apk_size
          echo $(./tools/check-size.sh | tail -1 | cut -d ',' -f2-) > ./apk_size/size.txt
      - uses: actions/upload-artifact@v3
        with:
          name: apk-size
          path: apk_size/size.txt
          retention-days: 5
